name: Deploy To Tencent OSS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:

    - name: Checkout current commit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Get base commit
      id: base-commit
      run: echo "BASE_COMMIT=$(cat base-commit)" >> $GITHUB_ENV

    - name: Build base version
      run: |
        # Store current commit hash
        CURRENT_COMMIT=$(git rev-parse HEAD)
        # Checkout base commit
        git checkout ${{ env.BASE_COMMIT }}
        # Build base version
        npm install
        npm run build
        # Save base build
        mv public base_build
        # Return to current commit
        git checkout $CURRENT_COMMIT

    - name: Build current version
      run: |
        npm install
        npm run build

    - name: Find changed files
      run: |
        # Create a list of changed files
        mkdir -p changed_files
        cd public
        find . -type f | while read file; do
          if [ ! -f "../base_build/$file" ] || ! cmp -s "$file" "../base_build/$file"; then
            echo "Changed or new file: $file"
            mkdir -p "../changed_files/$(dirname "$file")"
            cp "$file" "../changed_files/$file"
          fi
        done
        cd ..

    - name: Upload changed files to Tencent COS
      uses: TencentCloud/cos-action@v1
      with:
        secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
        secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        cos_bucket: ${{ secrets.COS_BUCKET }}
        cos_region: ${{ secrets.COS_REGION }}
        local_path: changed_files
        remote_path: /
        clean: false
